api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity','%kernel.project_dir%/config/api_platform']
    patch_formats:
        json: ['application/json']
    formats:
        json: ['application/json']
        multipart:
            mime_types: [ 'multipart/form-data' ]
    swagger:
        versions: [3]
    name_converter: Symfony\Component\Serializer\NameConverter\CamelCaseToSnakeCaseNameConverter
