framework:
    secret: '%env(APP_SECRET)%'
    http_method_override: false

    #esi: true
    #fragments: true
    php_errors:
        log: true

    serializer:
        mapping:
            paths: ['%kernel.project_dir%/config/serialization']

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
