version: 0.2

phases:
    install:
        runtime-versions:
            php: 8.0.2
    build:
        commands:
            - echo Installing Composer Dependencies on `date`
            - mkdir ./var
            - composer install -o --no-progress --no-suggest
    post_build:
        commands:
            - echo Build Completed on `date`