version: "3.3"
services:
    nginx:
        build:
            context: ./.docker/nginx
            dockerfile: Dockerfile
        container_name: nginx
        ports:
            - '8080:80'
            - '443:443'
        links:
            - php
        volumes:
            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www/html
    php:
        build:
            context: ./.docker/php
            dockerfile: Dockerfile
        container_name: php_ubot
        depends_on:
            -   db
        expose:
            - 9000
        volumes:
            - ./:/var/www/html
            - ./.docker/php/xdebug.ini:/etc/php8/conf.d/50_xdebug.ini
    db:
        image: mysql:8.0
        container_name: mysql_ubot
        environment:
            MYSQL_DATABASE: '${DATABASE_NAME}'
            MYSQL_USER: '${DATABASE_USER}'
            MYSQL_PASSWORD: '${DATABASE_PASSWORD}'
            MYSQL_ROOT_PASSWORD: '${DATABASE_ROOT_PASSWORD}'
        ports:
            - '9906:3306'
        volumes:
            - mysql_ubot:/var/lib/mysql
volumes:
    mysql_ubot:
