App\Entity\Receiver:
    attributes:
        id:
            groups: ['receiver:read']
        name:
            groups: ['receiver:read', 'receiver:create', 'receiver:update']
        description:
            groups: ['receiver:read', 'receiver:create', 'receiver:update']
        bankAccount:
            groups: ['receiver:read', 'receiver:create', 'receiver:update']
        locations:
            groups: ['receiver:read', 'receiver:create', 'receiver:update']
        imagePath:
            groups: ['receiver:read', 'receiver:create', 'receiver:update']
        industry:
            groups: ['receiver:read', 'receiver:create', 'receiver:update']
        internationalShipping:
            groups: ['receiver:read', 'receiver:create', 'receiver:update']
        links:
            groups: ['receiver:read', 'receiver:create']
        donationDescription:
            groups: ['receiver:read', 'receiver:create', 'receiver:update']
        images:
            groups: ['receiver:read', 'receiver:create', 'receiver:update']
        position:
            groups: ['receiver:read', 'receiver:create', 'receiver:update']
