parameters:
    uploads_directory: '%kernel.project_dir%/uploads'
services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $awsAccessKey: '%env(AWS_ACCESS_KEY)%'
            $awsSecretKey: '%env(AWS_SECRET_KEY)%'
            $awsBucket: '%env(AWS_BUCKET_NAME)%'
            $awsBucketHost: '%env(AWS_S3_BUCKET_HOST)%'
            $cloudFrontHost: '%env(AWS_CLOUDFRONT_HOST)%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Controller\:
        resource: '../src/Controller'
        tags: [ 'controller.service_arguments' ]

    'Symfony\Component\Serializer\NameConverter\CamelCaseToSnakeCaseNameConverter': ~

    Doctrine\Migrations\Version\DbalMigrationFactory: ~
    App\Doctrine\MigrationFactoryDecorator:
        decorates: Doctrine\Migrations\Version\DbalMigrationFactory
        arguments:
          [
              '@App\Doctrine\MigrationFactoryDecorator.inner',
              '@Doctrine\Common\Persistence\ManagerRegistry',
          ]
