App\Entity\Link:
    collectionOperations:
        post: ~
    itemOperations:
        get: ~
        delete: ~
        patch:
            denormalization_context:
                groups: ['link:update']
